[package]
name = "cache-oblivious-btree-map"
version = "0.0.2"
edition = "2021"
description = "Cache oblivious BTreeMap."
license = "Apache-2.0"
repository = "https://github.com/cpcs/cache-oblivious-btree"

[dependencies]
num-rational = "0.4.1"
rand = "0.8.5"
